---
title: "Central American Migration"
author: "Ethan Tenison"
date: "2/6/2020"
output: html_document
---

```{r setup, message=FALSE}
library(ggplot2)
library(dplyr)
library(janitor)
library(tidyverse)
library(ggplot2)
library(viridis)
library(raster)
library(maptools)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(ggpubr)
library(cowplot)
library(scales)
```


# Plot of Central American Migrantion into the United States. 


```{r CA_pop_datacleaning}

options(scipen = 999)
df <- read.csv("census_numbers.csv", stringsAsFactors = FALSE)
df <- clean_names(df)
names(df) <- as.matrix(df[4, ])
df <- df[-1, ]
df <- df[6:238, 1:6]
df <- rename(df, country = "Region and country or area")
df$country <- as.character(df$country)
df <-filter(df,country %in% c("El Salvador", "Honduras", "Guatemala", "Nicaragua"))

df <-rename(
      df,
      "Country" = "country",
      "2000" = "2000*",
      "1990" = "1990*",
      "1980" = "1980*",
      "1970" = "1970*",
      "1960" = "1960*"
   )

df_2010 <- read.csv("./ACS_10_1YR_B05006_with_ann.csv")
names(df_2010) <- as.matrix(df_2010[1,])
df_2010 <- df_2010[-1,]
df_2010 <- clean_names(df_2010)
df_2010 <-dplyr::select(
      df_2010,
      "estimate_americas_latin_america_central_america_nicaragua",
      "estimate_americas_latin_america_central_america_honduras",
      "estimate_americas_latin_america_central_america_guatemala",
      "estimate_americas_latin_america_central_america_el_salvador"
   )
df_2010 <- rename(
      df_2010,
      "Nicaragua" = "estimate_americas_latin_america_central_america_nicaragua",
      "Honduras" = "estimate_americas_latin_america_central_america_honduras",
      "Guatemala" = "estimate_americas_latin_america_central_america_guatemala" ,
      "El Salvador" = "estimate_americas_latin_america_central_america_el_salvador"
   )
df_2010 <-gather(df_2010, Country, population, "Nicaragua":"El Salvador")
df_2010 <- mutate(df_2010, year = "2010")
#df_2010$year <- as.factor(df_2010$year)
df_2010$population <- as.numeric(df_2010$population)


df <- dplyr::select(df, "Country", "1960", "1970", "1980", "1990", "2000")
df <- gather(df, year, population, "1960":"2000")
df$population <- as.numeric(gsub(",", "", df$population))
df <- rbind(df, df_2010)
df$year <- as.numeric(df$year)

```

```{r ca_pop_ggplot}
plasma_pal <- c("#7E03A8FF","#0D0887FF", "#F89441FF", "#CC4678FF")
theme_set(theme_bw())
ggplot(data = df, aes(x = year, y = population, group = Country)) +
   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
         panel.background = element_blank(), axis.line = element_line(colour = "black")) +
   geom_line(aes(color = Country), size = 2) +
   geom_point(aes(color = Country)) +
   ggtitle("Population of foreign born Central Americans in the United States") +
   xlab("Year") +
   ylab("Population") +
   scale_y_continuous(label=comma) +
   labs(caption = "Data source: US Census")+
   scale_color_manual(values = plasma_pal) +
   geom_vline(xintercept = 1998, linetype = "dashed") +
   geom_segment(aes(
      x = 1994,
      y = 1000000,
      xend = 1997.5,
      yend = 1000000
   ),
   arrow = arrow(length = unit(0.5, "cm"))) +
   annotate(
      "text",
      x = 1989,
      y = 970000,
      label = expression("Hurricane Mitch \n", paste("hits Honduras")),
      size = 3.5
   ) +
   
   geom_vline(xintercept = 1979, linetype = "dashed") +
   geom_segment(aes(
      x = 1975,
      y = 500000,
      xend = 1978.5,
      yend = 500000
   ),
   arrow = arrow(length = unit(0.5, "cm"))) +
   annotate(
      "text",
      x = 1970,
      y = 450000,
      label = expression("Salvadoran \n", paste("Civil War begins")),
      size = 3.5
   ) 

ggsave("foreign_born_pop.png")

```

```{r HDI}
df <- read.csv("Human Development Index (HDI).csv", stringsAsFactors = FALSE)
names(df) <- as.matrix(df[1,])
df <- df[-1,]
df <- clean_names(df)
df$country[df$country == "United States"] <- "United States of America"

coords <- data.frame("long" =c(-90.4,-98.8,-91.7,-88.61,-86.94,-88.89,-85.04,-83.93,-79.55,-78.56,-77.36),
                "lat" = c(15.3,18.9,32.26,17.1,14.78,13.62,12.66,9.88,9.11,21.80,18.12),
                "HDI" = c(0.651,0.767,0.920,0.720,0.623,0.667,0.651,0.794,0.795,0.778,0.726))

##Setting up the map
theme_set(theme_bw())

world <- ne_countries(scale='medium',returnclass = 'sf')
class(world)

world <- left_join(world, df, by = c("sovereignt"="country"))
world[is.na(world)] <- 0
world$x2018[world$x2018 == ".."] <- "0"
world<-world[!(world$x2018 <.6),]
world$x2018 <- as.numeric(world$x2018)

(ggulf <- ggplot(data = world) +
      geom_sf(aes(fill = x2018)) +
      annotate(geom = "text", x = -90, y = 26, label = "Gulf of Mexico", 
               fontface = "italic", color = "grey22", size = 6) +
      coord_sf(xlim = c(-102.15, -74.12), ylim = c(7.65, 33.97), expand = FALSE) +
      scale_fill_viridis(option = "plasma", direction = -1) +
      theme( axis.title.x = element_blank(), 
            axis.title.y = element_blank(), panel.background = element_rect(fill = "azure"), 
            panel.border = element_rect(fill = NA))+
      geom_text(data = coords, x = coords$long, y = coords$lat, label= coords$HDI, nudge_x = 0.25,
                nudge_y = 0.25, check_overlap = T) +
      labs(fill = "HDI"))
      

ggsave("central_america_hdi.png")
```



```{r hdi_latin_am}
df <- read.csv("Human Development Index (HDI).csv", stringsAsFactors = FALSE)
names(df) <- as.matrix(df[1,])
df <- df[-1,]
df <- clean_names(df)
df$country[df$country == "United States"] <- "United States of America"
df$country[df$country == "Venezuela (Bolivarian Republic of)"] <- "Venezuela"
df$country[df$country == "Bolivia (Plurinational State of)"] <- "Bolivia"
	

##Setting up the map
theme_set(theme_bw())

world <- ne_countries(scale='medium',returnclass = 'sf')
class(world)

world <- left_join(world, df, by = c("sovereignt"="country"))
world[is.na(world)] <- 0
world$x2018[world$x2018 == ".."] <- "0"
world$x2018 <- as.numeric(world$x2018)
world<-world[!(world$x2018 <.6),]

(gamerica <- ggplot(data = world) +
      geom_sf(aes(fill = x2018)) +
      coord_sf(xlim = c(-120.15, -30.12), ylim = c(-60, 45), expand = FALSE) +
      scale_fill_viridis(option = "plasma", direction = -1) +
      theme( axis.title.x = element_blank(), 
            axis.title.y = element_blank(), panel.background = element_rect(fill = "azure"), 
            panel.border = element_rect(fill = NA))+
      labs(fill = "HDI"))

ggsave("latin_america_hdi.png")
```


```{r arranging_hdi_maps}
combined_hdi <- ggarrange(ggulf, gamerica, ncol = 2, nrow = 1, widths =c(1,1), heights = c(1,1))
combined_hdi
                 
```